#!/data/data/com.termux/files/home/.local/bin/python
from __future__ import annotations

import argparse
import contextlib
import json
import shutil
import subprocess
import sys
import tempfile
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from pathlib import Path

from colorama import Fore, Style, init

init(autoreset=True)


@dataclass
class MinifyStats:
    path: Path
    original_size: int
    minified_size: int
    success: bool
    error: str = ""

    @property
    def ratio(self) -> float:
        if self.original_size == 0:
            return 0.0
        return (1 - self.minified_size / self.original_size) * 100

    @property
    def saved(self) -> int:
        return self.original_size - self.minified_size


class HTMLMinifier:
    DEFAULT_CONFIG = {
        "collapseBooleanAttributes": True,
        "collapseInlineTagWhitespace": True,
        "collapseWhitespace": True,
        "conservativeCollapse": False,
        "decodeEntities": True,
        "html5": True,
        "includeAutoGeneratedTags": False,
        "keepClosingSlash": False,
        "minifyCSS": True,
        "minifyJS": True,
        "minifyURLs": True,
        "preserveLineBreaks": False,
        "preventAttributesEscaping": False,
        "processConditionalComments": True,
        "processScripts": ["text/html"],
        "quoteCharacter": '"',
        "removeComments": True,
        "removeEmptyAttributes": True,
        "removeEmptyElements": True,
        "removeRedundantAttributes": True,
        "removeScriptTypeAttributes": True,
        "removeStyleLinkTypeAttributes": True,
        "removeTagWhitespace": True,
        "sortAttributes": True,
        "sortClassName": True,
        "trimCustomFragments": True,
        "useShortDoctype": True,
    }

    def __init__(self):
        self.config = self.DEFAULT_CONFIG.copy()
        self._check_dependencies()

    @staticmethod
    def _check_dependencies() -> None:
        if not shutil.which("html-minifier-terser"):
            print(
                f"{Fore.RED}Error: html-minifier-terser is not installed.{Style.RESET_ALL}"
            )
            print(
                f"{Fore.YELLOW}Install it with: npm install -g html-minifier-terser{Style.RESET_ALL}"
            )
            sys.exit(1)

    @staticmethod
    def _fix_doctype(content: str) -> str:
        import re

        content = re.sub(r"<!(doctype)(html)", r"<!\1 \2", content, flags=re.IGNORECASE)
        content = re.sub(r"<!(DOCTYPE)(HTML)", r"<!\1 \2", content)
        return content

    @staticmethod
    def _post_process(content: str) -> str:
        content = HTMLMinifier._fix_doctype(content)
        import re

        content = re.sub(
            r"(</(?:span|a|strong|em|b|i|code|label)>)"
            r"(<(?:span|a|strong|em|b|i|code|label))",
            r"\1 \2",
            content,
        )
        return content

    def _build_cli_args(self, config_file: Path) -> list[str]:
        args = ["html-minifier-terser", "--config-file", str(config_file)]
        return args

    def minify_file(self, file_path: Path) -> MinifyStats:
        config_file = None
        try:
            original_size = file_path.stat().st_size
            with tempfile.NamedTemporaryFile(
                mode="w", suffix=".json", delete=False, encoding="utf-8"
            ) as f:
                json.dump(self.config, f)
                config_file = Path(f.name)
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()
            cmd = self._build_cli_args(config_file)
            process = subprocess.run(
                cmd, input=content, capture_output=True, text=True, encoding="utf-8"
            )
            if process.returncode != 0:
                return MinifyStats(
                    path=file_path,
                    original_size=original_size,
                    minified_size=original_size,
                    success=False,
                    error=f"Minification failed: {process.stderr.strip()}",
                )
            minified_content = self._post_process(process.stdout)
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(minified_content)
            minified_size = file_path.stat().st_size
            return MinifyStats(
                path=file_path,
                original_size=original_size,
                minified_size=minified_size,
                success=True,
            )
        except Exception as e:
            return MinifyStats(
                path=file_path,
                original_size=0,
                minified_size=0,
                success=False,
                error=str(e),
            )
        finally:
            if config_file and config_file.exists():
                with contextlib.suppress(Exception):
                    config_file.unlink()

    @staticmethod
    def find_html_files(paths: list[Path]) -> list[Path]:
        html_files = []
        for path in paths:
            if not path.exists():
                print(
                    f"{Fore.YELLOW}Warning: Path '{path}' does not exist. Skipping.{Style.RESET_ALL}"
                )
                continue
            if path.is_file():
                if path.suffix.lower() in [".html", ".htm"]:
                    html_files.append(path)
                else:
                    print(
                        f"{Fore.YELLOW}Warning: '{path}' is not an HTML file. Skipping.{Style.RESET_ALL}"
                    )
            elif path.is_dir():
                html_files.extend(path.rglob("*.html"))
                html_files.extend(path.rglob("*.htm"))
            else:
                print(
                    f"{Fore.YELLOW}Warning: '{path}' is neither a file nor a directory. Skipping.{Style.RESET_ALL}"
                )
        return sorted(set(html_files))

    def minify_paths(self, paths: list[Path], max_workers: int = 4) -> None:
        html_files = self.find_html_files(paths)
        if not html_files:
            print(f"{Fore.YELLOW}No HTML files found to minify.{Style.RESET_ALL}")
            return
        total_files = len(html_files)
        print(
            f"\n{Fore.CYAN}Found {total_files} HTML file(s) to minify{Style.RESET_ALL}"
        )
        print(f"{Fore.CYAN}{'=' * 42}{Style.RESET_ALL}\n")
        stats_list: list[MinifyStats] = []
        successful = 0
        failed = 0
        total_original = 0
        total_minified = 0
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_to_file = {
                executor.submit(self.minify_file, file_path): file_path
                for file_path in html_files
            }
            for future in as_completed(future_to_file):
                stats = future.result()
                stats_list.append(stats)
                if stats.success:
                    successful += 1
                    total_original += stats.original_size
                    total_minified += stats.minified_size
                    self._print_file_stats(stats)
                else:
                    failed += 1
                    self._print_error(stats)
        self._print_summary(
            total_files, successful, failed, total_original, total_minified
        )

    def minify_directory(self, directories: list[Path], max_workers: int = 4) -> None:
        self.minify_paths(directories, max_workers)

    def _print_file_stats(self, stats: MinifyStats) -> None:
        try:
            rel_path = stats.path.relative_to(Path.cwd())
        except ValueError:
            rel_path = stats.path
        original_kb = stats.original_size / 1024
        minified_kb = stats.minified_size / 1024
        saved_kb = stats.saved / 1024
        if stats.ratio > 30:
            ratio_color = Fore.GREEN
        elif stats.ratio > 10:
            ratio_color = Fore.YELLOW
        else:
            ratio_color = Fore.RED
        print(
            f"{Fore.GREEN}✓{Style.RESET_ALL} {Fore.WHITE}{rel_path}{Style.RESET_ALL}\n"
            f"  {Fore.BLUE}Original: {original_kb:.2f} KB{Style.RESET_ALL}  "
            f"{ratio_color}→ {minified_kb:.2f} KB{Style.RESET_ALL}  "
            f"{Fore.MAGENTA}(-{saved_kb:.2f} KB, {ratio_color}{stats.ratio:.1f}%{Style.RESET_ALL}{Fore.MAGENTA}){Style.RESET_ALL}"
        )

    def _print_error(self, stats: MinifyStats) -> None:
        try:
            rel_path = stats.path.relative_to(Path.cwd())
        except ValueError:
            rel_path = stats.path
        print(
            f"{Fore.RED}✗ {rel_path}{Style.RESET_ALL}\n  {Fore.RED}Error: {stats.error}{Style.RESET_ALL}"
        )

    def _print_summary(
        self,
        total: int,
        successful: int,
        failed: int,
        total_original: int,
        total_minified: int,
    ) -> None:
        total_saved = total_original - total_minified
        overall_ratio = (
            (total_saved / total_original * 100) if total_original > 0 else 0
        )
        original_mb = total_original / (1024 * 1024)
        minified_mb = total_minified / (1024 * 1024)
        saved_mb = total_saved / (1024 * 1024)
        print(f"\n{Fore.CYAN}{'=' * 42}{Style.RESET_ALL}")
        print(f"{Fore.CYAN}Summary{Style.RESET_ALL}")
        print(f"{Fore.CYAN}{'=' * 42}{Style.RESET_ALL}")
        print(f"{Fore.WHITE}Files processed:  {total}{Style.RESET_ALL}")
        print(f"{Fore.GREEN}✓ Successful:     {successful}{Style.RESET_ALL}")
        if failed > 0:
            print(f"{Fore.RED}✗ Failed:         {failed}{Style.RESET_ALL}")
        print(f"{Fore.WHITE}Original size:    {original_mb:.2f} MB{Style.RESET_ALL}")
        print(f"{Fore.WHITE}Minified size:    {minified_mb:.2f} MB{Style.RESET_ALL}")
        print(
            f"{Fore.GREEN}Total saved:      {saved_mb:.2f} MB ({overall_ratio:.1f}%){Style.RESET_ALL}"
        )
        print(f"{Fore.CYAN}{'=' * 42}{Style.RESET_ALL}\n")


def main():
    parser = argparse.ArgumentParser(
        description="Minify HTML files recursively using html-minifier-terser",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                          
  %(prog)s file1.html file2.html    
  %(prog)s public/ dist/            
  %(prog)s index.html src/          
  %(prog)s --workers 8 src/
        """,
    )
    parser.add_argument(
        "paths",
        nargs="*",
        default=["."],
        help="Files or directories to process (default: current directory)",
    )
    parser.add_argument(
        "-w",
        "--workers",
        type=int,
        default=4,
        help="Number of parallel workers (default: 4)",
    )
    parser.add_argument(
        "--no-color", action="store_true", help="Disable colored output"
    )
    args = parser.parse_args()
    if args.no_color:
        init(strip=True, autostop=False)
    paths = [Path(p).resolve() for p in args.paths]
    minifier = HTMLMinifier()
    minifier.minify_paths(paths, max_workers=args.workers)


if __name__ == "__main__":
    raise SystemExit(main())
