#!/data/data/com.termux/files/home/.local/bin/python
from __future__ import annotations
import os
from collections import OrderedDict
from pathlib import Path


def get_current_path():
    return os.environ.get("PATH", "")


def parse_path_values(path_string):
    if not path_string:
        return []
    return path_string.split(":")


def deduplicate_paths(path_list):
    seen = set()
    deduplicated = OrderedDict()
    for path in path_list:
        if path and path not in seen:
            seen.add(path)
            deduplicated[path] = True
    return list(deduplicated.keys())


def generate_bash_config(paths):
    if not paths:
        return ("", "")
    assignments = []
    for i, path in enumerate(paths, 1):
        assignments.append(f'P{i}="{path}"')
    path_vars = ":".join([f"$P{i}" for i in range(1, len(paths) + 1)])
    export_statement = f"export PATH={path_vars}:$PATH"
    return (assignments, export_statement)


def read_bashrc(bashrc_path):
    if bashrc_path.exists():
        with open(bashrc_path, encoding="utf-8") as f:
            return f.read()
    return ""


def find_and_remove_old_config(content):
    marker_start = "# === PATH DEDUPLICATION (AUTO-GENERATED) ===\n"
    marker_end = "# === END PATH DEDUPLICATION ===\n"
    start_idx = content.find(marker_start)
    if start_idx != -1:
        end_idx = content.find(marker_end, start_idx)
        if end_idx != -1:
            end_idx += len(marker_end)
            content = content[:start_idx] + content[end_idx:]
    return content.rstrip() + "\n"


def append_to_bashrc(bashrc_path, assignments, export_statement):
    content = read_bashrc(bashrc_path)
    content = find_and_remove_old_config(content)
    new_config = "\n# === PATH DEDUPLICATION (AUTO-GENERATED) ===\n"
    new_config += "# This section was automatically generated by path_dedup.py\n"
    new_config += (
        "# Edit this section or regenerate by running: python3 path_dedup.py\n\n"
    )
    for assignment in assignments:
        new_config += assignment + "\n"
    new_config += "\n" + export_statement + "\n"
    new_config += "# === END PATH DEDUPLICATION ===\n"
    with open(bashrc_path, "a", encoding="utf-8") as f:
        f.write(new_config)


def display_results(original_paths, deduplicated_paths, assignments, export_statement):
    print("-" * 40)
    print("PATH DEDUPLICATION RESULTS")
    print("-" * 40)
    print("\n📊 Summary:")
    print(f"   Original PATH entries:      {len(original_paths)}")
    print(f"   Deduplicated entries:       {len(deduplicated_paths)}")
    print(
        f"   Duplicates removed:         {len(original_paths) - len(deduplicated_paths)}"
    )
    print("\n📝 Generated Variables:")
    for i, assignment in enumerate(assignments, 1):
        print(f"   {assignment}")
    print("\n📤 Export Statement:")
    print(f"   {export_statement}")
    print("\n🔍 Details of Deduplicated Paths:")
    for i, path in enumerate(deduplicated_paths, 1):
        print(f"   P{i} = {path}")
    if len(original_paths) > len(deduplicated_paths):
        print("\n⚠️  Removed Duplicates:")
        removed = set(original_paths) - set(deduplicated_paths)
        seen = set()
        for path in original_paths:
            if path in removed and path not in seen:
                count = original_paths.count(path)
                if count > 1:
                    print(f"   {path} (appeared {count} times)")
                    seen.add(path)
    print("\n" + "=" * 40)


def backup_bashrc(bashrc_path):
    if bashrc_path.exists():
        backup_path = bashrc_path.with_suffix(".bashrc.backup")
        if not backup_path.exists():
            import shutil

            shutil.copy2(bashrc_path, backup_path)
            print(f"✓ Backup created: {backup_path}")
            return True
    return False


def main():
    print("\n🚀 Clash of Clans TH18 BASE deduplicator...")
    home_dir = Path.home()
    bashrc_path = home_dir / ".bashrc"
    print("\n📌 Reading current PATH environment variable...")
    path_string = get_current_path()
    if not path_string:
        print("❌ Error: PATH environment variable is empty!")
        return
    original_paths = parse_path_values(path_string)
    print(f"✓ Found {len(original_paths)} PATH entries")
    print("\n🔄 Deduplicating PATH values...")
    deduplicated_paths = deduplicate_paths(original_paths)
    print(f"✓ Deduplicated to {len(deduplicated_paths)} unique entries")
    print("\n⚙️  Generating bash configuration...")
    assignments, export_statement = generate_bash_config(deduplicated_paths)
    if not assignments:
        print("❌ Error: No valid paths to export!")
        return
    display_results(original_paths, deduplicated_paths, assignments, export_statement)
    print("\n💾 Preparing to save to ~/.bashrc")
    response = input("   Continue? (yes/no): ").strip().lower()
    if response not in ["yes", "y"]:
        print("❌ Cancelled. No changes made.")
        return
    backup_bashrc(bashrc_path)
    print("\n✍️  Appending configuration to ~/.bashrc...")
    try:
        append_to_bashrc(bashrc_path, assignments, export_statement)
        print(f"✓ Successfully saved to {bashrc_path}")
    except Exception as e:
        print(f"❌ Error writing to {bashrc_path}: {e}")
        return
    print("\n" + "=" * 40)
    print("🎉 SUCCESS! Configuration saved to ~/.bashrc")
    print("-" * 40)
    print("\n📋 To activate the new PATH configuration, run one of:")
    print("   source ~/.bashrc")
    print("   # or")
    print("   . ~/.bashrc")
    print("\n💡 Then verify with:")
    print("   echo $PATH")
    print("\n✨ Done!")


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\n\n❌ Interrupted by user.")
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
