[tool.ruff]
target-version = "py312"
[tool.ruff.lint]
extend-select = ["UP006", "UP007", "F401"]
[project]
dependencies = [
    "dh @ file:///data/data/com.termux/files/home/projects/py/dh/src",
]
[tool.ty]

[environment]
extra-search-path = [
    "/data/data/com.termux/files/home/projects/py/dh/src",
]
