#!/data/data/com.termux/files/home/.local/bin/python
import random
import os
import sys
from pathlib import Path


dns_providers = {
    "DNS.Watch": ["84.200.69.80", "84.200.70.40"],
    "Comodo Secure DNS": ["8.26.56.26", "8.20.247.20"],
    "Level3 DNS": ["209.244.0.3", "209.244.0.4"],
    "Yandex DNS": ["77.88.8.8", "77.88.8.1"],
    "Cloudflare DNS": ["1.1.1.1", "1.0.0.1"],
    "Open DNS": ["208.67.222.222", "208.67.220.220"],
    "Google DNS": ["8.8.8.8", "8.8.4.4"],
}


def set_dns():
    name, servers = random.choice(list(dns_providers.items()))
    infile = Path.home() / ".resolv.conf"
    content = f"# Generated by DNS Switcher\n# Selected: {name}\n"
    for ip in servers:
        content += f"nameserver {ip}\n"

    try:
        infile.write_text(content, encoding="utf-8")
        print(f"Successfully switched DNS to: {name}")
        print(f"Nameservers: {', '.join(servers)}")
    except Exception as e:
        print(f"Error updating DNS: {e}")


if __name__ == "__main__":
    set_dns()
